package com.spark.electronics_store.model;

public enum ProductCategory {
    SMARTPHONES,
    LAPTOPS,
    TABLETS,
    DESKTOPS,
    PC_COMPONENTS,
    MONITORS,
    PRINTERS_SCANNERS,
    STORAGE,
    NETWORKING,
    PERIPHERALS_ACCESSORIES,
    AUDIO_HEADPHONES,
    AUDIO_SPEAKERS,
    CAMERAS,
    GAMING_CONSOLES,
    GAMING_ACCESSORIES,
    TV_HOME_THEATER,
    SMART_HOME,
    WEARABLES,
    DRONES,
    SMALL_APPLIANCES,
    ELECTRIC_MOBILITY,
    SOFTWARE
}
